---
name: "Bug Report"
description: "Submit a bug report"
labels: ["bug"]
assignees: ["luketainton"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: This is not a feature request
          required: true
        - label: I added a descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find one.
          required: true
  - type: input
    id: ipilot-version
    attributes:
      label: iPilot Version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is the issue you are experiencing?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      description: If you do not provide a way to reproduce the issue, your issue will likely be closed.
      label: How can the maintainer reproduce the issue?
      placeholder: A clear step-by-step guide on how to reproduce the issue.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Deployment
      description: What Deployment system are you using?
      multiple: true
      options:
        - Docker
        - Native (Windows)
        - Native (MacOS)
        - Native (Linux)
        - Other
    validations:
      required: true
  - type: textarea
    id: os-details
    attributes:
      label: Deployment Details
      description: You can add more details about your operating system here, in particular if you chose "Other".
