name: SAST Scan
on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

jobs:  
  scan:
    name: Scan
    uses: AppThreat/sast-scan-action@master
    with:
      output: reports
      type: go
  
  upload:
    name: Upload reports
    uses: actions/upload-artifact@v1
    with:
      name: sast-scan-reports
      path: reports
